### ISSUE TITLE
Unable to Build with Manifest AutoBackup = true

### ISSUE THREAD

**Issue by searchy2** [shiburagi/Drawer-Behavior#10]
This library's Manifest includes an unnecessary attribute autoBackup="true" which conflicts with apps that set autoBackup="false".

**Comment by searchy2** [comment]
Fixed by #11

**Comment by searchy2** [comment]
Any update?

**Comment by shiburagi** [comment]
Thanks for your contribution.

Sorry i didn't notice this issue and I already published it.
``
implementation 'com.infideap.drawerbehavior:drawer-behavior:0.0.7'
``

**Comment by searchy2** [comment]
Thank you for the merge and great library!
