### ISSUE TITLE
How to change ImageView size and TextViewSize of menuItem

### ISSUE THREAD

**Issue by nikeru8** [shiburagi/Drawer-Behavior#12]
as Title,
How to change ImageView size and TextViewSize of menuItem?

 help

**Comment by shiburagi** [comment]
hi, 

you can add custom theme like this in styles.xml
```xml
  <style name="NavigationTheme" parent="AppTheme">
        <item name="listPreferredItemHeightSmall">60dp</item><!-- menu item height- vary as u need -->
    </style>
```

then,  set that theme at drawer :
```xml
<android.support.design.widget.NavigationView
        .
        .
        .
        android:theme="@style/NavigationTheme" />
```

or you can refer here,

https://stackoverflow.com/questions/44644588/how-to-customise-navigation-drawer-item-height

**Comment by nikeru8** [comment]
thanks
also can override design_navigation_icon_size
 <dimen name="design_navigation_icon_size" tools:override="true">50dp</dimen>
