### ISSUE TITLE
androidX compatibility issue

### ISSUE THREAD

**Issue by Tinyhuge** [shiburagi/Drawer-Behavior#16]
Hey Developer this Lib is awesome and working fine till **Migration** to Latest **androidx(jetpack, replacement of android support library)...**

**Please update this Awesome Library and make Compatible with Latest androidX !!**

excited to see this awesome Lib with Latest Androidx support..
  Thank you !!

**Comment by shiburagi** [comment]
i will try migrate it asap

**Comment by Tinyhuge** [comment]
we are waiting, Thanks in Advance 😃

**Comment by shiburagi** [comment]
Maybe you can try this version:

`implementation 'com.infideap.drawerbehavior:drawer-behavior:0.2.1'`

**Comment by Tinyhuge** [comment]
I tried. working absolutely fine..!!
 Thank you again for your time.
