### ISSUE TITLE
Not Support RTL

### ISSUE THREAD

**Issue by RHoumaidy** [shiburagi/Drawer-Behavior#2]
when the local of the device set to RTL like (Arabic) the activity still slides to right, while it should slide to left

**Comment by shiburagi** [comment]
just change the gravity to 'end'.

**Comment by shiburagi** [comment]
```xml
android:layout_gravity="right" 
```
or you can refer here

https://stackoverflow.com/questions/18547277/how-to-set-navigation-drawer-to-be-opened-from-right-to-left
