### ISSUE TITLE
Problem with opening and scaling when support rtl is false but input language change to rtl language like persian

### ISSUE THREAD

**Issue by EhsanSetayesh** [shiburagi/Drawer-Behavior#27]
i use advance6 sample to open drawer from right and scale view to left but support rtl is false .

it works fine when input language is english but when i change input language to persian it does not work properly when support rtl is false drawer open from right but view is scale to right too so they move against each other.

please help.

**Comment by shiburagi** [comment]
can you try remove this code in app/src/main/res/layout/activity_advance6.xml
```xml
    app:chainUseRtl="true"
```

**Comment by EhsanSetayesh** [comment]
yes i tried it acutally i tried many ways without any improvement .
finally to make it work for my situation i set supportrtl to true and like activity_advance6 layout i set openDrawer and layout_gravity and all settings to START  but to prevent my other layouts and my custom nav layout from changing i set style to all my parent layout and set layoutdirection to ltr .
please let me know if you fix this bug on later versions .

**Comment by shiburagi** [comment]
u may try using version 1.0,4, this issue should be fixed.
