### ISSUE TITLE
Bug in adding content view

### ISSUE THREAD

**Issue by yasharpm** [shiburagi/Drawer-Behavior#4]
Hi,

I think you need to add the following lines to your `AdvanceDrawerLayout`.

```
    @Override
    public void addView(View child, ViewGroup.LayoutParams params) {
        child.setLayoutParams(params);
        addView(child);
    }
```

Your code fails to intercept child views that are not added to layout by an `include` tag. Since other views have their width and height set, the other method gets called and you miss them.

**Comment by yasharpm** [comment]
My folks forked your code recently. I just doubted that maybe they have forked an older version. Anyway I hope this helps in case the bug really exists.

**Comment by shiburagi** [comment]
Okay, i'll check it.

**Comment by shiburagi** [comment]
I already add your code to AdvanceDrawerLayout and thanks for your help.
