### ISSUE TITLE
Is there any way to disable the swipe-to-open gesture?

### ISSUE THREAD

**Issue by marconealberto** [shiburagi/Drawer-Behavior#5]
I want to open the drawer programmatically and not have the user swipe from left or right.
Is there any way to do that?
Thank you

**Comment by shiburagi** [comment]
Yes,
‘’’java
drawer.openDrawer(Gravity.START); // Open left drawer

drawer.openDrawer(Gravity.END); // Open right drawer
‘’’

To disable gesture swipe
‘’’java
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, leftDrawerView);
‘’’

**Comment by shiburagi** [comment]
Yes,
To open drawer
```java
drawer.openDrawer(Gravity.START); // Open left drawer

drawer.openDrawer(Gravity.END); // Open right drawer
```

To close drawer
```java
drawer.closeDrawer(Gravity.START); // Open left drawer

drawer.closrDrawer(Gravity.END); // Open right drawer
```

To disable gesture swipe
```java
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, leftDrawerView);
```

**Comment by shiburagi** [comment]
To open drawer
```java
drawer.openDrawer(Gravity.START); // Open left drawer

drawer.openDrawer(Gravity.END); // Open right drawer
```

To close drawer
```java
drawer.closeDrawer(Gravity.START); // Close left drawer

drawer.closeDrawer(Gravity.END); // Close right drawer
```

To disable swipe gesture
```java
drawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, leftDrawerView);
```

**Comment by shiburagi** [comment]
For more solution on disable swipe, you may refer on link below
https://stackoverflow.com/questions/17025957/disable-gesture-listene
