### ISSUE TITLE
How set click method for menu item

### ISSUE THREAD

**Issue by ali-bagheri** [shiburagi/Drawer-Behavior#6]
How can set click method for menu item without use android:onClick=""?

**Comment by shiburagi** [comment]
same link drawer layout from support library, you may implement **NavigationView.OnNavigationItemSelectedListener** class and override below code,

``java
@SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.

        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

``

**Comment by nikeru8** [comment]
@Override
    public boolean onNavigationItemSelected(MenuItem item) {
      if(item.getItemId()){
//do something
}
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }
